language: cpp
compiler:
    - clang
notifications:
    email:
        - zach.allaun@gmail.com
        - daniel@danielespeset.com
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/julianightlies -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
    - git config --global user.name "Zach Allaun"
    - git config --global user.email "zach.allaun@gmail.com"
    - git submodule update --init --recursive
script:
    - julia -e "Pkg.init()"
    - julia -e 'Pkg.add("BinDeps")'
    - julia -e 'Pkg.add("Calendar")'
    - julia -e 'Pkg.add("HttpParser")'
    - julia -e 'Pkg.add("FactCheck")'
    - mkdir -p ~/.julia/HttpCommon
    - cp -R ./* ~/.julia/HttpCommon/
    - julia -e 'Pkg.fixup("HttpCommon")'
    - julia ~/.julia/HttpCommon/test/test.jl
